### ISSUE TITLE
[BUG] $Z_{2^n}^+$ není formálně těleso

### ISSUE THREAD

**Issue by mikison9** [mvojacek/aps-skripta#1]
**URL odkaz na kapitoly**
https://skripta.vojacek.org/03_alu/03_odcitani.html

**Popsání chyby a její řešení**
$Z_{2^n}^+$ není formálně těleso.

**Screenshoty**
![image](https://github.com/user-attachments/assets/9945d09c-200f-42ce-b2df-44757019dc95)

**Comment by mvojacek** [comment]
a taky prepsat na mathbaby Z

**Comment by mikison9** [comment]
Ehm, doopravdy znamená makro \mathbb blacboard bold font.

![image](https://github.com/user-attachments/assets/8cabcd8e-167a-4d91-8055-8321b1da7be8)

**Comment by mvojacek** [comment]
ok ale kdyz ses tak chytrej tak proc kdyz jsem hledal jak udelat aby math font co neni sikmo tak jedno řešení je frenchmath https://tex.stackexchange.com/a/134925

![frenchmath](https://steamuserimages-a.akamaihd.net/ugc/963116578370774090/2B15A58E6C62E7F6868230D0EEC49A32F1C39684/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)
